image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:      
#  - name: application-startup
#    before: sudo docker-up
#    init: mvn package -DskipTests
#    command: java -jar target/*.jar

  - name: docker-daemon
    before: sudo docker-up

  - name: docker-container
    before:
      echo 'Waiting for docker daemon to start' &&
      until docker info &> /dev/null; do sleep 1; done;
    init:
      docker-compose up
    
  - name: applicaion-start
    before:
        echo 'Waiting for docker daemon to start' &&
        until docker info &> /dev/null; do sleep 1; done;
    init:
      mvn clean package -DskipTests
    command: 
      java -jar target/*.jar


vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot