version: "3.7"

services:
  postgres:
    container_name: cm-app-postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cmapp_service
      POSTGRES_USER: cmapp
      POSTGRES_PASSWORD: cmapp
    ports:
      - 5432:5432
      
volumes:
  postgres_data:
    driver: local