version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: cm-app-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cmapp_service
      POSTGRES_USER: cmapp
      POSTGRES_PASSWORD: cmapp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
