spring:
  application:
    name: CM Services
  jpa:
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    hibernate:
      ddl-auto: "none"
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: "classpath:db/db-changelog-master.xml"
    user: "cmapp"
    password: "cmapp"
  datasource:
    username: cmapp
    password: cmapp
    url: jdbc:postgresql://localhost:5432/cmapp_service
server:
  port: 8080
logging:
  level:
    hu.vereba: DEBUG
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
