spring:
  application:
    name: CM Services
  data:
    mongodb:
      uri: mongodb://cmuser:cmpass@localhost:27017/cmdb
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    hu.vereba: DEBUG
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
