spring:
  application:
    name: CM Services
  liquibase:
    enabled: true
    change-log: "classpath:db/db-changelog-master.xml"
    user: "sa"
    password: ""
    url: "jdbc:h2:mem:cmapp_service"
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:cmapp_service;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  jpa:
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    hibernate:
      ddl-auto: "none"
    generate-ddl: false
  h2:
    console:
      enabled: true
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    hu.vereba: DEBUG
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
