version: '3.9'

services:
  mongodb:
    image: mongo:8
    container_name: cm-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cmdbadmin
      MONGO_INITDB_ROOT_PASSWORD: mysecretpass
      MONGO_INITDB_DATABASE: cmdb
    volumes:
      #- ./mongodb_data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
