version: "3.7"

services:
  cm-app-service:
    container_name: cm-app-service
    image: demo/cm-app-service
    build:
      context: ../..
      dockerfile: ../../Dockerfile
      args:
        execution_env: $EXEC_ENV
    networks:
      - cmnet
    ports:
      - $SERVICES_PORT:8080

networks:
  cmnet:

volumes:
  postgres_data:
    driver: local